version: '3.3'

services:
   wordpress:
     image: microsoft/multicontainerwordpress
     volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
     ports:
       - "8000:80"

     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} 
   redis:
     image: redis:3-alpine
     restart: always
RUN apt-get update \
   && apt-get install -y --no-install-recommends openssh-server \
   && echo "root:Docker!" | chpasswd
COPY sshd_config /etc/ssh/
EXPOSE 2222 80
```docker
COPY startup /opt/startup
...
RUN chmod 755 /opt/startup/init_container.sh
...
ENTRYPOINT ["/opt/startup/init_container.sh"]
```
