version: '3.3'

services:
   wordpress:
     image: microsoft/multicontainerwordpress
     volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wp-config.php:/var/www/html/wp-config.php
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/wp-content:/var/www/html/wp-content
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/.htaccess:/var/www/html/.htaccess
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} 
   redis:
     image: redis:3-alpine
     restart: always
