apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  containers:

   - image: redis:3-alpine
     name: redis

   - image: microsoft/multicontainerwordpress
     name: wordpress
     ports:
     - containerPort: 80
       name: wordpress
     volumeMounts:
      - name: appservice-storage
        mountPath: /var/www/html
        subPath: /site/wwwroot
  volumes:
    - name: appservice-storage
      hostConfig:
        path: ${WEBAPP_STORAGE_HOME}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${WEBAPP_STORAGE_HOME}//site/wwwroot"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
